### ISSUE TITLE
HiveOS libcudart.so.11.0

### ISSUE THREAD

**Issue by bukum86** [h9-dev/ironfish-miner#2]
Error which i get by running miner is 

./hpool-miner-ironfish-cuda: error while loading shared libraries: libcudart.so.11.0: cannot open shared object file: No s
uch file or directory

Mentioned file exists and it is located in /hive/lib/libcudart.so.11.0

Thanks

**Comment by trying2016** [comment]
The version of cuda needs to install the running environment of cuda, you can try our version of OpenCl

**Comment by bukum86** [comment]
I tried it as well, windows version of opencl miner works on nvidia cards, but on linux it does not

**Comment by trying2016** [comment]
You can also try to install the cuda support manually
Driver update: https://www.nvidia.cn/Download/index.aspx?lang=cn
Cuda support: https://developer.nvidia.com/cuda-downloads

**Comment by bukum86** [comment]
I am running now 510.60.02 nvidia driver version and CUDA 11.6

**Comment by kudabelangfxrace** [comment]
is look like hiveos not yet have cuda 11.7 supported.

**Comment by bukum86** [comment]
Is there possibility to create version of miner which will run on older cuda version ?

**Comment by trying2016** [comment]
Older versions of cuda may have low computing power, we recommend using cuda version 11.7

**Comment by bukum86** [comment]
Its not possible to update cuda on HiveOS. I get this error
![unknown](https://user-images.githubusercontent.com/42100418/189126167-f38fe90f-1d21-4cd6-b000-1762217edbf4.png)

**Comment by trying2016** [comment]
We are adapting HiveOS and will provide installation packages

**Comment by bukum86** [comment]
Thats great news ! Thank you very much

**Comment by trying2016** [comment]
Version 1.0.3 already supports HiveOS system
![image](https://user-images.githubusercontent.com/20046296/189298776-fac14cf7-73f6-4e46-9547-8e3cf4d2cf81.png)

https://github.com/hpool-dev/ironfish-miner/releases/download/1.0.3/hpool-miner-ironfish-v1.0.3.1.tar.gz

**Comment by trying2016** [comment]
https://www.hpool.in/help/tutorial/44
