### ISSUE TITLE
v1.0.2 multi GPU hashrate issue

### ISSUE THREAD

**Issue by bukum86** [h9-dev/ironfish-miner#3]
I run miner on 8 GPU system, 8x6800. Average speed is 9.68GHs (1.21GHs per card). Miner have been running for several hours now and reported speed at hpool is only 1.1GHs. All GPU are on 100% load and normal mining power consumption (meaning they are hashing)

**Comment by trying2016** [comment]
Is the miner's apiKey filled in correctly?

**Comment by trying2016** [comment]
You can restart the miner and see if the log shows that the ApiKey is correct

**Comment by bukum86** [comment]
Yes it is, otherwise miner wont appear in my personal center on hpool, right? I am not sure if the hashrate I see on hpool is reported hash rate by miner or real hashrate based on submitted shares.

**Comment by trying2016** [comment]
The miner speed is too high, causing overflow. It will not affect the actual contribution points and income. You can see the actual computing power of miner at https://www.hpool.in/center/contribution. Display problem and we will fix it as soon as possible

**Comment by bukum86** [comment]
yeah, on contribution page it looks OK. its more pool side problem rather than miner problem. Cheers

**Comment by kudabelangfxrace** [comment]
problem known..it will fix asap

**Comment by trying2016** [comment]
We have fixed the overflow issue, you can download a new miner and try again

**Comment by kudabelangfxrace** [comment]
> We have fixed the overflow issue, you can download a new miner and try again

0 h/s on personal center

machine 8Ghs

**Comment by bukum86** [comment]
Same for me, now shows 0h/s on personal center

**Comment by trying2016** [comment]
Sorry, please try again with version 1.0.2-3
https://github.com/hpool-dev/ironfish-miner/releases/tag/1.0.2
